# Generated by Django 4.1 on 2022-09-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_order_order_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
