# Generated by Django 4.1.1 on 2022-09-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='book',
            new_name='book_id',
        ),
    ]
