# Generated by Django 4.1.1 on 2022-09-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_book_rental_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.IntegerField(default=0),
        ),
    ]
