# Generated by Django 4.1.1 on 2022-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_rental_extension_date_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserve_status',
            field=models.IntegerField(default=0),
        ),
    ]
