# Generated by Django 4.1.1 on 2022-09-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_reserve_reserve_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='reserve_status',
        ),
    ]
