# Generated by Django 4.1.1 on 2022-09-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_reserve_reserve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='available_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='reserve_status',
            field=models.IntegerField(default=0),
        ),
    ]
