# Generated by Django 4.1.1 on 2022-09-23 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0008_reserve_available_date_reserve_reserve_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='overdue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdue_period', models.IntegerField()),
                ('pay_dated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overdue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
