# Generated by Django 4.1.1 on 2022-09-28 04:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0011_overdue_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveAlarmLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('book_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('alarm_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='overdue',
            name='pay_dated',
        ),
        migrations.AddField(
            model_name='overdue',
            name='overdue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='overdue',
            name='pay_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rental',
            unique_together={('book_id', 'user_id', 'rental_date')},
        ),
    ]
