# Generated by Django 4.1.1 on 2022-09-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_reservealarmlog_remove_overdue_pay_dated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateTimeField(null=True),
        ),
    ]
