# Generated by Django 4.1.1 on 2022-09-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_remove_overdue_book_id_remove_overdue_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
