# Generated by Django 4.1 on 2022-09-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_reason',
            field=models.TextField(null=True),
        ),
    ]
