# Generated by Django 4.1.1 on 2022-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
